name: Broken Setup
description: Checkout repositories, install common dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: BrokenSource/BrokenSource
        submodules: recursive
        fetch-depth: 0

    - name: Checkout main
      run: git submodule foreach --recursive 'git checkout main || true'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Sync dependencies
      run: uv sync --all-packages

    - name: Get workflow options
      run: uv run python ./Broken/Version.py >> $GITHUB_ENV
