name: Broken Setup
description: Checkout repositories, install common dependencies

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: BrokenSource/BrokenSource
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Sync dependencies
      run: uv sync --all-packages
      shell: bash

    - name: Get workflow options
      run: uv run python ./Broken/Version.py >> $GITHUB_ENV
      shell: bash
