name: Broken Setup
description: Checkout repositories, install common dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: BrokenSource/BrokenSource
        submodules: recursive
        fetch-depth: 0

    - name: Checkout main
      run: git submodule foreach --recursive 'git checkout main || true'
      shell: bash

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Sync dependencies
      run: uv sync --all-packages
      shell: bash

    - name: Get workflow options
      run: uv run ./broken/version.py >> $GITHUB_ENV
      shell: bash
