services:

  broken-base: &common
    image: broken-base:local
    pull_policy: never
    build: &build
      context: .
      dockerfile: docker/broken-base.dockerfile
      args: &args
        TORCH_VERSION: ${TORCH_VERSION:-2.7.0}
        TORCH_FLAVOR:  ${TORCH_FLAVOR:-cpu}
        EDITABLE:      ${EDITABLE:-0}

    volumes:
      # - ./docker/workspace:/root/.local/share/BrokenSource
      - /usr/lib/wsl:/usr/lib/wsl

    # Docker "--gpus all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

    # Podman "--gpus all"
    devices:
      - nvidia.com/gpu=all

# ------------------------------------------------------------------------------------------------ #

  _pyaket:
    image: broken-base:pyaket
    build:
      args:
        UV_SYNC: "--package pyaket"
        FEATURE_COMPILER: 1
        FEATURE_RUST:     1
        <<: *args
      <<: *build

  pyaket:
    image: pyaket:latest
    pull_policy: never
    build:
      dockerfile: docker/pyaket.dockerfile
    depends_on:
      - _pyaket

# ------------------------------------------------------------------------------------------------ #

  _glinfo:
    image: broken-base:glinfo
    build:
      args:
        FEATURE_OPENGL:   1
        FEATURE_MONOREPO: 0
        <<: *args
      <<: *build

  glinfo:
    image: glinfo:latest
    build:
      dockerfile: docker/glinfo.dockerfile
    depends_on:
      - _glinfo
    <<: *common

# ------------------------------------------------------------------------------------------------ #

  _shaderflow:
    image: broken-base:shaderflow
    build:
      args:
        UV_SYNC: "--package shaderflow"
        FEATURE_OPENGL: 1
        FEATURE_PULSE:  1
        FEATURE_FFMPEG: 1
        <<: *args
      <<: *build

  shaderflow:
    image: shaderflow:latest
    build:
      dockerfile: docker/shaderflow.dockerfile
    depends_on:
      - _shaderflow
    <<: *common

# ------------------------------------------------------------------------------------------------ #

  _depthflow:
    image: broken-base:depthflow
    build:
      dockerfile: docker/broken-base.dockerfile
      args:
        UV_SYNC: "--package depthflow"
        FEATURE_OPENGL:   1
        FEATURE_VULKAN:   1
        FEATURE_PULSE:    1
        FEATURE_FFMPEG:   1
        FEATURE_UPSCAYL:  1
        FEATURE_DEPTHMAP: 1
        FEATURE_TORCH:    1
        <<: *args
      <<: *build

  depthflow:
    image: depthflow:latest-${TORCH_FLAVOR:-cpu}
    build:
      dockerfile: docker/depthflow.dockerfile
    depends_on:
      - _depthflow
    ports:
      - "7860:7860"
      - "8000:8000"
    expose:
      - "7860"
      - "8000"
    <<: *common

# ------------------------------------------------------------------------------------------------ #
