services:

  broken-base: &common
    image: broken-base:local
    pull_policy: never
    build: &build
      context: .
      dockerfile: docker/broken-base.dockerfile
      args: &args
        FEATURE_OPENGL:   ${FEATURE_OPENGL:-0}
        FEATURE_VULKAN:   ${FEATURE_VULKAN:-0}
        FEATURE_PULSE:    ${FEATURE_PULSE:-0}
        FEATURE_FFMPEG:   ${FEATURE_FFMPEG:-0}
        FEATURE_UPSCAYL:  ${FEATURE_UPSCAYL:-0}
        FEATURE_DEPTHMAP: ${FEATURE_DEPTHMAP:-0}
        FEATURE_TORCH:    ${FEATURE_TORCH:-0}
        TORCH_VERSION:    ${TORCH_VERSION:-2.7.0}
        TORCH_FLAVOR:     ${TORCH_FLAVOR:-cpu}
        EDITABLE:         ${EDITABLE:-0}
    volumes:
      # - ./docker/workspace:/root/.local/share/BrokenSource
      - /usr/lib/wsl:/usr/lib/wsl

    # Docker "--gpus all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

    # Podman "--gpus all"
    # devices:
    #   - nvidia.com/gpu=all

# ------------------------------------------------------------------------------------------------ #

  _pyaket:
    image: broken-base:pyaket
    build:
      args:
        <<: *args
      <<: *build

  pyaket:
    image: pyaket:latest
    pull_policy: never
    build:
      dockerfile: projects/Pyaket/dockerfile
    depends_on:
      - _pyaket

# ------------------------------------------------------------------------------------------------ #

  _glinfo:
    image: broken-base:glinfo
    build:
      args:
        FEATURE_OPENGL:   1
        FEATURE_MONOREPO: 0
        <<: *args
      <<: *build

  glinfo:
    image: glinfo:latest
    build:
      dockerfile: docker/glinfo.dockerfile
    depends_on:
      - _glinfo
    <<: *common

# ------------------------------------------------------------------------------------------------ #

  _shaderflow:
    image: broken-base:shaderflow
    build:
      args:
        FEATURE_OPENGL: 1
        FEATURE_PULSE:  1
        FEATURE_FFMPEG: 1
        <<: *args
      <<: *build

  shaderflow:
    image: shaderflow:latest
    build:
      dockerfile: docker/shaderflow.dockerfile
    depends_on:
      - _shaderflow
    <<: *common

# ------------------------------------------------------------------------------------------------ #

  _depthflow:
    image: broken-base:depthflow
    build:
      dockerfile: docker/broken-base.dockerfile
      args:
        FEATURE_OPENGL:   1
        FEATURE_VULKAN:   1
        FEATURE_PULSE:    1
        FEATURE_FFMPEG:   1
        FEATURE_UPSCAYL:  1
        FEATURE_DEPTHMAP: 1
        FEATURE_TORCH:    1
        <<: *args
      <<: *build

  depthflow:
    image: depthflow:latest-${TORCH_FLAVOR:-cpu}
    build:
      dockerfile: docker/depthflow.dockerfile
    depends_on:
      - _depthflow
    ports:
      - "7860:7860"
      - "8000:8000"
    expose:
      - "7860"
      - "8000"
    <<: *common

# ------------------------------------------------------------------------------------------------ #
