services:

  _common: &common
    image: broken-base:local
    pull_policy: never
    build: &build
      context: .
      dockerfile: docker/broken-base.dockerfile
      args: &args
        TORCH_VERSION: ${TORCH_VERSION:-2.7.0}
        TORCH_FLAVOR:  ${TORCH_FLAVOR:-cpu}
        EDITABLE:      ${EDITABLE:-0}

    volumes:

      # Nvidia drivers on Windows
      - /usr/lib/wsl:/usr/lib/wsl

    # Docker "--gpus all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

    # Podman "--gpus all"
    devices:
      - nvidia.com/gpu=all

# ------------------------------------------------------------------------------------------------ #

  glinfo:
    image: glinfo:local
    build:
      dockerfile: docker/glinfo.dockerfile
      args:
        <<: *args
    <<: *common

  pyaket:
    image: pyaket:local
    build:
      dockerfile: docker/pyaket.dockerfile
      args:
        UV_SYNC: "--package pyaket"
        <<: *args

  shaderflow:
    image: shaderflow:local
    build:
      dockerfile: docker/shaderflow.dockerfile
      args:
        UV_SYNC: "--package shaderflow"
        <<: *args
    <<: *common

  depthflow:
    image: depthflow:local
    build:
      dockerfile: docker/depthflow.dockerfile
      args:
        UV_SYNC: "--package depthflow"
        <<: *args
    ports:
      - "7860:7860"
      - "8000:8000"
    expose:
      - "7860"
      - "8000"
    <<: *common

# ------------------------------------------------------------------------------------------------ #
