services:

  # Base images

  broken-base: &common
    image: broken-base
    pull_policy: never
    build:
      context: .
      dockerfile: Docker/broken-base.dockerfile
      args:
        TORCH_VERSION: ${TORCH_VERSION:-2.6.0}
        TORCH_FLAVOR: ${TORCH_FLAVOR:-cpu}

    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      # - ./Docker/Workspace:/root/.local/share/BrokenSource

    # "--gpus=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  # Sanity checks, assertions

  glinfo:
    image: glinfo
    pull_policy: never
    build:
      context: .
      dockerfile: Docker/glinfo.dockerfile
    depends_on:
      - broken-base
    <<: *common

  # Actual software

  shaderflow:
    image: shaderflow
    pull_policy: never
    build:
      context: .
      dockerfile: Docker/shaderflow.dockerfile
    depends_on:
      - broken-base
    <<: *common

  depthflow:
    image: depthflow
    pull_policy: never
    build:
      context: .
      dockerfile: Docker/depthflow.dockerfile
    depends_on:
      - broken-base
    ports:
      - "7860:7860"
      - "8000:8000"
    expose:
      - "7860"
      - "8000"
    <<: *common
