services:

  # Base images

  broken-base: &common
    image: broken-base-local
    build:
      context: .
      dockerfile: docker/base.dockerfile

    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - .:/app

    # "--gpus=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  # Sanity checks, assertions

  glinfo:
    image: glinfo-local
    build:
      context: .
      dockerfile: docker/glinfo.dockerfile
    depends_on:
      - broken-base
    <<: *common

  # Actual software

  shaderflow:
    image: shaderflow-local
    build:
      context: .
      dockerfile: docker/shaderflow.dockerfile
    depends_on:
      - broken-base
    <<: *common

  depthflow:
    image: depthflow-local
    build:
      context: .
      dockerfile: docker/depthflow.dockerfile
    depends_on:
      - broken-base
    ports:
      - "7860:7860"
    expose:
      - "7860"
    <<: *common
