name: docker-release
on:
  workflow_dispatch:
  push:
    paths:
      - "Broken/Version.py"

jobs:
  main:
    name: Build and push images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Login to ghcr.io
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Build and push images
        if: ${{env.GHA_DOCKER == 'True'}}
        run: uv run broken docker --push
