name: make-wheels
on:
  workflow_dispatch:

jobs:
  main:
    name: Release wheels
    runs-on: ubuntu-latest
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Make wheels
        run: uv build --wheel --package ${{github.event.repository.name}}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*
