name: make-pypi
on:
  workflow_dispatch:

jobs:
  main:
    name: Release wheels
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Make wheels
        run: uv build --wheel --all

      - name: Publish wheels
        run: uv publish dist/*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: build/wheels/*
