name: make-wheels
on:
  workflow_dispatch:
    inputs:
      publish:
        required: true
        type: boolean

jobs:
  main:
    name: Make wheels
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Make wheels
        run: uv build --wheel --package ${{github.event.repository.name}}

      - name: Publish wheels
        if: ${{ inputs.publish }}
        run: uv publish dist/*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*
