name: make-tag
on:
  workflow_dispatch:

jobs:
  main:
    name: Create git tag
    runs-on: ubuntu-latest
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Create tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a v$GHA_VERSION -m "Release v$GHA_VERSION"
          git push origin v$GHA_VERSION
