name: make-docker
on:
  workflow_dispatch:

jobs:
  main:
    name: Build and push images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Build and push images
        run: uv run broken docker --push --clean --regex depthflow
