name: make-pyaket
on:
  workflow_dispatch:

jobs:
  main:
    name: Compile on (${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    steps:
      - uses: BrokenSource/BrokenSource@main
        name: Broken Setup

      - name: Install gcc aarch64
        if: ${{matrix.os == 'ubuntu-22.04'}}
        run: sudo apt install -y gcc-aarch64-linux-gnu

      - name: Compile projects
        run: uv run broken workflow-pyaket

      - name: Upload releases
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-release
          path: release/*
